# fly.toml app configuration file generated for remy-api on 2024-12-03T14:29:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remy-api'
primary_region = 'ewr'

[build]

[deploy]
release_command = 'flask db upgrade'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
